title: Persona 4 Golden
description: Complete guide to P4G for the PS Vita
baseurl: "/" # the subpath of your site, e.g. /blog
permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]
search_enabled: true
#aux_links:
#  "Just the Docs on GitHub":
#    - "//github.com/pmarsceill/just-the-docs"
color_scheme: dark